---
title: "First Assignment"
author: "Malgorzata, Kevin, Johannes"
date: "December, 2018"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 11pt
geometry: margin=1in
---

## First Problem: (Simulation: Latent Variable, Probit Model):
$$
\begin{array} { l } 
{ \text { Consider the following JOINT distributions of random variables } X _ { 0 }  \&  \varepsilon _ { j } ^ { * } \text { (You must simulate } } \\ { \text { it as a joint (multivariate) normal distributions!). } } 
\end{array}
$$
$$
\left( \begin{array} { l }
{ X _ { 0 } } \\ { \varepsilon _ { 1 } ^ { * } } \end{array} \right) \sim N \left[ \left( \begin{array} { c } { 10 } \\ { 0 } \end{array} \right) , \left( \begin{array} { c c } { 2 ^ { 2 } } & { 0 } \\ { 0 } & { 1 } 
\end{array} \right) \right],
\left( \begin{array}
{ c } { X _ { 0 } } \\ { \varepsilon _ { 2 } ^ { * } } \end{array} \right) \sim N \left[ \left( \begin{array} { c } { 10 } \\ { 0 } \end{array} \right) , \left( \begin{array} { c c } { 2 ^ { 2 } } & { 0 } \\ { 0 } & { 2 ^ { 2 } } 
\end{array} \right) \right],
\left( \begin{array} { l }
{ X _ { 0 } } \\ { \varepsilon _ { 3 } ^ { * } } \end{array} \right) \sim N \left[ \left( \begin{array} { c } { 10 } \\ { 0 } \end{array} \right) , \left( \begin{array} { c c } { 2 ^ { 2 } } & { 3 } \\ { 3 } & { 2 ^ { 2 } } 
\end{array} \right) \right]
$$

with 

$$
\begin{array} { l } 
{ \beta _ { 0 } = - 30 } \\ { \beta _ { 1 } = 4 } \\
\\
{ Y _ { j } ^ { * } = \beta _ { 0 } + \beta _ { 1 } * X _ { 1 } + \varepsilon _ { j }} \\
\\
Y _ { j } = \left\{ \begin{array} { l l } { 1 \text { if } Y _ { j } ^ { * } > 0 } \\ { 0 , \text { otherwise } } \end{array} \right.\\
\\
j \in \{ 1,2,3 \}
\end{array}
$$


$$
\begin{array} { l } 
{ \text { a) [1P] Please simulate the three datasets (i.e.: }
Y _ { j } , X _ { 1 } , \varepsilon _ { j } ^ { * } ; j \in \{ 1,2,3 \} ) 
\text { with a sample } } \\ { \text { size of } 30000 \text { observations. For each of the three datasets, estimate a probit model } } 
\\ 
{ \text { of } 
\mathrm { Y } _ { \text { i } } \text { on } x _ { 1 } 
\text { and save the estimate for } \hat { \beta } _ { 1 } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { b) } 
[ 1.5 \mathrm { P } ] 
\text { Repeat a 400 times while saving all the different estimate in vectors for all } } 
\\
{ \text { three models (based on the three different populations). Plot the kernel density } } 
\\ 
{ \text { estimates for } \hat { \beta } _ { 1 } 
\text { based on the three populations next to each other. Describe shortly } } 
\\ 
{ \text { the choices you faced and made estimating the density functions. } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { b) } 
[ 1.5 \mathrm { P } ] 
\text { Repeat a 400 times while saving all the different estimate in vectors for all } }
\\ 
{ \text { three models (based on the three different populations). Plot the kernel density } } 
\\ 
{ \text { estimates for } \hat { \beta } _ { 1 } \text { based on the three populations next to each other. Describe shortly } } 
\\ 
{ \text { the choices you faced and made estimating the density functions. } } 
\end{array}
$$
```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { i. } [ 1.5 \mathrm { P } ] 
\text { Now concentrate on the kernel density plot based on the first } } 
\\ 
{ \text { population (i.e.: } Y _ { 1 } , X _ { 1 } , \varepsilon _ { 1 } ^ { * } ) 
\text { . Does the distribution of } \overline { \beta } _ { 1 } \text { conform to your } } 
\\ 
{ \text { expectations? More specifically, explain which distribution you would expect } } 
\\ 
{ \text { (and why) and whether the plotted density conform to that expectation (no } } 
\\ 
{ \text { formal tests necessary). } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { ii. } [ 1 \mathrm { P } ] 
\text { Compare the distributions of } \widehat { \beta _ { 1 } } 
\text { from the population } j = 1 
\text { to the } \widehat { \beta _ { 1 } } 
\text { from } } 
\\ 
{ \text { the population } j = 2 
\text { and } j = 3 , 
\text { respectively. Why do the means of the } } 
\\ 
{ \text { distributions differ? } } 
\end{array}
$$
```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { iii. } [ 1 \mathrm { P } ] 
\text { Compute the mean of } \widehat { \beta _ { 1 } } 
\text { from the population } j = 2 . 
\text { Can you explain, why } } 
\\ 
{ \text { the distribution of this particular } \overline { \beta _ { 1 } } 
\text { concentrate approximately around this value?} } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { Simulate again all three populations as you did in a. But this time, estimate and save the } } 
\\ 
{ \text { average marginal probability effect of } x _ { 1 } 
\text { . Repeat the estimation } 400 \text { times with a sample } } 
\\
{ \text { size of each iteration equaling } 30000 . } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { c) [1P] Analogously to b), plot the kernel density estimates for all three AMPE's. } } 
\\ 
{ \text { Determine the values around which the sample distributions are concentrated. } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { i. } [ 1.5 \mathrm { P } ] 
\text { Calculate the relative difference (in percent) between } \hat { E } [ A M P E | j = 1 ] } 
\\ 
{ \text { and } \hat { E } [ A M P E | j = 3 ] . 
{\text { Which estimate would you use to ascertain the effect of the variable } x _ { 1 } ? }} 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { ii. } [ 1.5 \mathrm { P } ] 
\text { Calculate the relative difference (in percent) between } \hat { E } [ A M P E | j = 1 ] } 
\\ 
{ \text { and } \hat { E } [ A M P E | j = 2 ] . } 
\end{array}
$$


```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { i. } 
[ 1.5 \mathrm { P } ] 
\text { Based on the results in b-ii) would you expect the differences observed} }
\\
{ \text {c-i) and  c-ii)? Please provide a detailed explanation for the observed results } }
\end{array}
$$


```{r, echo=FALSE}


```

$$
\pagebreak
$$

## Problem 2: (Marginal effects estimation & Interpretation):

$$
\begin{array} { l } 
{ \text { a) } }
[ 0.5 \mathrm { P } ]  
{\text { Can you learn anything from the estimated coefficients? Explain shortly.} }
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { b) } 
[ 0.5 \mathrm { P } ]  
\text { Are the } 
\mathrm { S.E. } 
\text { valid, or do you need to adjust them for heteroscedasticity? } } 
\\ 
{ \text { Explain. } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { c) } 
[ 2 \mathrm { P } ] 
\text { Re-estimate the model from a } ) 
\text { but this time include age in addition to } 1 \mathrm { d } 1 . } 
\\ 
{ \text { You see that the estimated coefficient of } 1 \mathrm { d } 1 
\text { changes. Explain why? Additionally, } } 
\\ 
{ \text { show that your explanation is supported by the data. } } 
\end{array}
$$

```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { d) Finally, estimate the model from a ) but include ld } 1 
\text { squared next to } 1 \mathrm { dl } \text { as a } } 
\\ 
{ \text { control variable. } } 
\end{array}
$$
```{r, echo=FALSE}


```

$$
\begin{array} { l } 
{ \text { v. } [ 1 \mathrm { P } ] 
\text { Are any of the effects computed in iv), ceteris paribus effects? Explain } } 
\\ 
{ \text { shortly. } }
\end{array}
$$
